# Test against verious Node.js versions
environment:
  matrix:
    # Minimum node version
    - nodejs_version: "6"
    # Most common node version (for UF community)
    - nodejs_version: "7"
    # Latest node version
    - nodejs_version: ""

# Install scripts. (runs after repo cloning)
install:
  # Base build version on package.json version
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off